{{- if .Values.namespaces }}
{{- range $ns := .Values.namespaces }}
{{- if $ns.enabled }}
{{ $name:= printf "%s" .name}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $name | quote}}
  annotations:
    openshift.io/display-name: {{ $ns.displayName | quote }}
    openshift.io/description: {{ $ns.description | quote }}
  {{- if $ns.labels }}
  labels:
  {{- range $k,$v := $ns.labels }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
